import * as yup from 'yup';

const categorySchema = yup.object().shape({
  // categoryId is generated by the server, so no need to validate it on the client side.
  name: yup.string()
    .max(50, 'Name must be at most 50 characters long.')
    .required('Name is required.'),
  description: yup.string()
    .max(255, 'Description must be at most 255 characters long.'),
  costPerKilo: yup.number()
    .min(0, 'Cost per kilo must be at least 0.')
    .required('Cost per kilo is required.'),
});

export default categorySchema;
